app/libs/forgot_password/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email


class ForgotPasswordForm(FlaskForm):
    email = StringField(
        'Email', validators=(DataRequired(), Email()))


class ResetPasswordForm(FlaskForm):
    new_password = PasswordField('New Password')

app/libs/forgot_password/__init__.py
from uuid import uuid4
from app.models.user import User
from .model import ForgotPasswordToken


class InvalidTokenException(Exception):
    pass


def decode(token):
    '''Decode a token generated in forgot_password'''
    [id, token] = token.split('_')
    try:
        return ForgotPasswordToken.validate_and_delete_token(id, token)
    except ForgotPasswordToken.DoesNotExist:
        raise InvalidTokenException('Token could not be decoded')


def forgot_password(email, sender):
    '''Generate a forgot password token and pass it to sender function
    The sender function should take two argument (the token and the user)
    and it's expected to send the token to the user with email 'email' via
    email/sms/or other.
    '''
    user = User.objects.get(email=email)
    token_string = uuid4().hex
    token = ForgotPasswordToken(
        user=user,
        token=token_string
    )
    token.save()
    sender('{}_{}'.format(token.id, token_string), user)

app/libs/forgot_password/views.py
from flask import (
    Blueprint,
    flash,
    render_template,
    redirect,
    url_for
)
from app.models.user import User
from .forms import (
    ForgotPasswordForm,
    ResetPasswordForm
)
from . import (
    forgot_password as forgot_password_util,
    decode,
    InvalidTokenException
)

bp = Blueprint('forgot_password', __name__, template_folder='templates')


@bp.route('/forgot-password', methods=['GET', 'POST'])
def forgot_password():
    form = ForgotPasswordForm()

    if form.validate_on_submit():
        email = form.email.data
        forgot_password_util(
            email,
            sender=__sender)

    return render_template(
        'forgot.html',
        form=form
    )


@bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    form = ResetPasswordForm()

    if form.validate_on_submit():
        try:
            user = decode(token)
            password = form.new_password.data
            user.update(
                password=User.hash_password(password).decode('utf-8')
            )
            flash('Password reset!', 'success')
        except InvalidTokenException:
            flash('The link is invalid or expired', 'error')
            return redirect(url_for('main.index'))

    return render_template(
        'reset.html',
        form=form,
        token=token
    )


def __sender(token, user):
    raise Exception(
        'Add a sender function to forgot_password_util call \n'
        'Token: {}'.format(token)
    )

app/libs/forgot_password/templates/forgot.html
{% extends 'layout.html' %}
{% block title %}Forgot Password{% endblock %}
{% block content %}

<div class="row">
  <div class="col-lg-offset-3 col-lg-6">
    <form method="post" action="{{ url_for('forgot_password.forgot_password') }}">
      {{ form.csrf_token }}
      <div class="form-group {% if form.email.errors %}has-error{% endif %}">
        {{ form.email(class="form-control", placeholder="Email") }}
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-default">Forgot Password</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

app/libs/forgot_password/templates/reset.html
{% extends 'layout.html' %}
{% block title %}Forgot Password{% endblock %}
{% block content %}

<div class="row">
  <div class="col-lg-offset-3 col-lg-6">
    <form method="post" action="{{ url_for('forgot_password.reset_password', token=token) }}">
      {{ form.csrf_token }}
      <div class="form-group {% if form.new_password.errors %}has-error{% endif %}">
        {{ form.new_password(class="form-control", placeholder="New Password") }}
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-default">Set New Password</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}