app/models/post.py
from datetime import datetime

from . import db
from .user import User
from .comment import Comment


class Post(db.Document):
    author = db.ReferenceField(User, reverse_delete_rule=db.CASCADE)
    title = db.StringField(max_length=80, required=True)
    body = db.StringField()
    comments = db.EmbeddedDocumentListField(Comment)
    created_at = db.DateTimeField(default=datetime.utcnow)
    updated_at = db.DateTimeField(default=datetime.utcnow)

    def __repr__(self):
        return '<Post: {0}>'.format(self.title)

app/forms/post.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired
from wtforms.widgets import TextArea


class PostForm(FlaskForm):
    title = StringField('title', validators=(DataRequired(),))
    body = StringField('body', widget=TextArea())

app/views/admin.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user, login_required

from ..forms.post import PostForm
from ..models.post import Post


bp = Blueprint('admin', __name__)

@bp.route('/login')
def login():
    return render_template('admin/login.html')


@bp.route('')
# @login_required
def posts():
    posts = Post.objects.all()
    return render_template('admin/index.html', posts=posts)


@bp.route('/new', methods=['GET', 'POST'])
# @login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        post = Post(
            author=current_user.id,
            title=form.title.data,
            body=form.body.data)
        post.save()
        flash('Post created', 'success')
        return redirect(url_for('admin.posts'))

    return render_template(
        'admin/form.html',
        form=form,
        endpoint=url_for('.new_post'))


@bp.route('/edit/<id>', methods=['GET', 'POST'])
# @login_required
def edit_post(id):
    post = Post.objects.get(pk=id)
    form = PostForm(obj=post)

    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.save()
        flash('Post updated', 'success')
        return redirect(url_for('admin.posts'))

    return render_template(
        'admin/form.html',
        form=form,
        endpoint=url_for('.edit_post', id=post.id))


@bp.route('/delete/<id>')
# @login_required
def delete_post(id):
    Post.objects(id=id).delete()
    flash('Post deleted', 'success')
    return redirect(url_for('admin.posts'))

app/templates/index.html
{% extends 'layout.html' %}
{% block title %}Recent Posts{% endblock %}
{% block content %}

<div class="row">
  <div class="col-lg-12">
    {% if posts %}
      {% for post in posts %}
        <h2><a href="{{ url_for('main.post', id=post.id) }}">{{ post.title }}</a></h2>
        <p>{{ post.body }}</p>
      {% endfor %}
    {% else %}
      <p>You don't have any posts yet! <a href="{{ url_for('admin.login') }}">Login</a> and create some!</p>
    {% endif %}
  </div>
</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}Home{% endblock %} - Flask Starter</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{{ url_for('static', filename='js/html5shiv.min.js') }}"></script>
      <script src="{{ url_for('static', filename='js/respond.min.js') }}"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('admin.manage_posts') }}">Admin</a></li>
            {% else %}
              <li><a href="{{ url_for('admin.login') }}">Login</a></li>
            {% endif %}
          </ul>
        </nav>
        <h3 class="text-muted"><a href="{{ url_for('main.index') }}">Flask Starter</a></h3>
      </div>

      {% with messages = get_flashed_messages(with_categories=True) %}
        {% for category, message in messages %}
          {% if category == 'error' %}
            <div class="alert alert-danger">{{ message }}</div>
          {% else %}
            <div class="alert alert-success">{{ message }}</div>
          {% endif %}
        {% endfor %}
      {% endwith %}

      {% block content %}{% endblock %}

      <footer class="footer">
        <p>&copy; Flask Starter</p>
      </footer>
    </div> <!-- /container -->

    <script src="{{ url_for('static', filename='js/bootstrap.main.js') }}"></script>
  </body>
</html>

app/templates/post.html
{% extends 'layout.html' %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

<div class="row">
  <div class="col-lg-12">
    <h1>{{ post.title }}</h1>
    <p>{{ post.body }}</p>
    <small>By {{ post.author.email }}</small>
  </div>
</div>

{% endblock %}

app/templates/protected.html
{% extends 'layout.html' %}

{% block title %}Protected{% endblock %}

{% block content %}
<h1>Yay!</h1>
<p>You made it to the protected page :D</p>
{% endblock %}

app/templates/register.html
{% extends 'layout.html' %}
{% block title %}Register{% endblock %}
{% block content %}

<div class="row">
  <div class="col-lg-offset-3 col-lg-6">
    <form method="post" action="{{ url_for('user.register') }}">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.first_name(class="form-control", placeholder="First name") }}
      </div>
      <div class="form-group">
        {{ form.last_name(class="form-control", placeholder="Last name") }}
      </div>
      <div class="form-group {% if form.email.errors %}has-error{% endif %}">
        {{ form.email(class="form-control", placeholder="Email") }}
        {% for error in form.email.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="form-group {% if form.password.errors %}has-error{% endif %}">
        {{ form.password(class="form-control", placeHolder="Password") }}
        {% for error in form.password.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-default">Register</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}